[project]
name = "llm-proxy-cli"
version = "0.1.0"
description = "Communication with LLM with CLI"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-generativeai>=0.8.5",
    "python-dotenv>=1.1.1",
]
