# セキュリティ設定ファイル
# LLM-Proxy-CLI のセキュリティ機能の設定

# デフォルト設定
default:
  security_level: "medium"
  enable_input_scanning: true
  enable_output_scanning: true
  enable_rate_limiting: true
  max_requests_per_minute: 60
  log_security_events: true

# セキュリティレベル別設定
security_levels:
  low:
    enable_input_scanning: false
    enable_output_scanning: false
    enable_rate_limiting: true
    max_requests_per_minute: 120
  
  medium:
    enable_input_scanning: true
    enable_output_scanning: true
    enable_rate_limiting: true
    max_requests_per_minute: 60
    input_scanners:
      - PromptInjection
      - BanSubstrings
      - Secrets
    output_scanners:
      - BanSubstrings
      - Sensitive
  
  high:
    enable_input_scanning: true
    enable_output_scanning: true
    enable_rate_limiting: true
    max_requests_per_minute: 30
    input_scanners:
      - PromptInjection
      - BanSubstrings
      - Secrets
      - BanTopics
      - Toxicity
    output_scanners:
      - BanSubstrings
      - Sensitive
      - Toxicity

# カスタムルール設定
custom_rules:
  # 禁止するサブストリング
  banned_substrings:
    - "password"
    - "secret"
    - "key"
    - "token"
    - "api_key"
    - "private_key"
    - "ssh_key"
    - "access_token"
    - "bearer_token"
  
  # 禁止するトピック
  banned_topics:
    - "violence"
    - "hate"
    - "self-harm"
    - "suicide"
    - "terrorism"
    - "drugs"
    - "weapons"
  
  # 許可する言語
  allowed_languages:
    - "en"
    - "ja"
  
  # 機密情報のパターン
  sensitive_patterns:
    - r"\b\d{4}[- ]?\d{4}[- ]?\d{4}[- ]?\d{4}\b"  # クレジットカード番号
    - r"\b\d{3}-\d{2}-\d{4}\b"  # SSN
    - r"\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b"  # メールアドレス
    - r"\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b"  # IPアドレス

# ログ設定
logging:
  level: "INFO"
  format: "%(asctime)s - %(levelname)s - %(message)s"
  file: "security.log"
  max_file_size: "10MB"
  backup_count: 5
  # LLM-Guardのログを抑制
  suppress_llm_guard_logs: true
  suppress_urllib3_logs: true
  suppress_requests_logs: true
  suppress_httpx_logs: true

# レート制限設定（改善版）
rate_limiting:
  window_size: 60  # 秒
  max_requests: 60  # 1分間に60リクエストまで許可
  burst_size: 10
  retry_after: 300  # 秒
  # より柔軟な制限設定
  adaptive_limiting: true
  # 連続リクエスト間の最小間隔（秒）
  min_interval: 1.0 